Repository openshift-knative/eventing-kafka, pull requests merged in 2021-03, with the labels that each got.

#76 Add mirror-upstream-branches script for automatic release creation
  openshift/release/mirror-upstream-branches.sh
  openshift/release/update-to-head.sh
Labels: approved

#78 Fix typo in update-ci.sh script
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#79 Fix typo in update-ci.sh script
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#82 Update ci targets (master branch)
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#81 Update ci targets to only 47
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#84 Rename to branch to main
  README.md
  openshift/release/create-release-branch.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#87 Trigger ci
  ci
Labels: approved, lgtm

#89 Registry update 0.21.0
  openshift/release/generate-release.sh
  openshift/release/knative-eventing-kafka-channel-ci.yaml
  openshift/release/knative-eventing-kafka-distributed-channel-ci.yaml
  openshift/release/knative-eventing-kafka-source-ci.yaml
Labels: approved, lgtm

#94 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#92 :bookmark: we dont need these on main
  openshift/release/knative-eventing-kafka-channel-ci.yaml
  openshift/release/knative-eventing-kafka-distributed-channel-ci.yaml
  openshift/release/knative-eventing-kafka-source-ci.yaml
Labels: approved, lgtm

#97 Explicit names for install functions
  openshift/e2e-common.sh
Labels: approved, lgtm

#100 Using matching eventing for tests
  openshift/e2e-common.sh
Labels: approved, lgtm

#101 Using matching eventing for tests
  openshift/e2e-common.sh
Labels: approved, lgtm

#102 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#104 Use KnativeEventing for the tracing, and patch it, not replace
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#116 [0.20] Use the latest version of product offering
  openshift/ci-operator/build-image/Dockerfile
  openshift/e2e-common.sh
Labels: approved

#117 [MAIN] Use the latest version of product offering
  openshift/e2e-common.sh
Labels: approved, lgtm

#110 [0.21] Remove GH Actions
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm

#108 Remove Noise
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm

#118 [0.21] Using serverless 1.13
  openshift/e2e-common.sh
Labels: approved, lgtm

#119 Clean-up and use proper eventing via operator
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved

#120 [0.21] Use eventing from operator 0.21
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#129 [0.21] Update generated yamls 0.21
  openshift/release/knative-eventing-kafka-channel-ci.yaml
Labels: approved

#130 [0.20] More clean up
  openshift/e2e-common.sh
  openshift/release/knative-eventing-kafka-channel-ci.yaml
Labels: approved, lgtm
