Repository openshift-knative/eventing-kafka, pull requests merged in 2021-04, with the labels that each got.

#135 Disable repo_gpgcheck for kube repo in build image
  openshift/ci-operator/build-image/kubernetes.repo
Labels: approved

#134 [v0.20.0] Backport of Update target pod IPs when dispatcher pods scale (knative-sandbox/eventing-kafka#496)
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/lister.go
  pkg/channel/consolidated/status/status.go
  pkg/channel/consolidated/status/status_test.go
Labels: approved, lgtm

#127 [0.19] Removing noise from upstream
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved

#136 [0.19] Disable repo_gpgcheck for kube repo in build image
  openshift/ci-operator/build-image/kubernetes.repo
Labels: approved, lgtm

#140 Backported #509
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/dispatcher/kafka_subscription.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
Labels: approved, lgtm

#141 [0.21] Slinky backport 509
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/dispatcher/kafka_subscription.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
Labels: approved, lgtm

#143 [0.20] Backport of PR #524 Run KafkaSource smokes in upgrade test
  test/e2e-common.sh
  test/e2e/kafka_source.go
  test/e2e/kafka_source_test.go
  test/upgrade/README.md
  test/upgrade/continual.go
  test/upgrade/installation/githead.go
  test/upgrade/installation/stable.go
  test/upgrade/postdowngrade.go
  test/upgrade/postupgrade.go
  test/upgrade/preupgrade.go
  test/upgrade/smoke.go
  test/upgrade/suite.go
Labels: approved, lgtm

#145 Ping build kafka
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
  ci
  openshift/e2e-common.sh
Labels: approved, lgtm

#146 Fixing the registry... once more
  openshift/e2e-common.sh
Labels: approved, lgtm

#151 [0.22] Backport of Run KafkaSource smokes in upgrade test (knative-sandbox#524)
  test/e2e-common.sh
  test/e2e/kafka_source.go
  test/e2e/kafka_source_test.go
  test/upgrade/README.md
  test/upgrade/continual.go
  test/upgrade/installation/githead.go
  test/upgrade/installation/stable.go
  test/upgrade/postdowngrade.go
  test/upgrade/postupgrade.go
  test/upgrade/preupgrade.go
  test/upgrade/smoke.go
  test/upgrade/suite.go
Labels: approved, lgtm

#150 [0.21] Backport of Run KafkaSource smokes in upgrade test (knative-sandbox#524)
  test/e2e-common.sh
  test/e2e/kafka_source.go
  test/e2e/kafka_source_test.go
  test/upgrade/README.md
  test/upgrade/continual.go
  test/upgrade/installation/githead.go
  test/upgrade/installation/stable.go
  test/upgrade/postdowngrade.go
  test/upgrade/postupgrade.go
  test/upgrade/preupgrade.go
  test/upgrade/smoke.go
  test/upgrade/suite.go
Labels: approved, lgtm

#153 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#162 [0.20] Use CE connection args available, instead of hardcoded values (#440)
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
Labels: approved, lgtm

#164 [0.20] Only return true in probe verifier if all partitions found
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/status/status.go
Labels: approved, lgtm

#165 [0.21] Cherrypick - Use CE connection args available, instead of hardcoded values
  pkg/channel/consolidated/dispatcher/dispatcher.go
Labels: approved, lgtm

#160 Backport v1alpha1 hacks
  config/channel/resources/kafkachannel-crd.yaml
  config/post-install/clusterrole.yaml
  config/post-install/placeholder.go
  config/post-install/serviceaccount.yaml
  config/post-install/storage-version-migrator.yaml
  hack/release.sh
  hack/tools.go
  pkg/apis/messaging/v1beta1/kafka_channel_defaults.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/modules.txt
Labels: approved, lgtm

#169 Forcing to use obsolete channel to make sure migration works
  test/upgrade/test_main.go
Labels: approved, lgtm

#170 [0.21] Setting retries & replication options with easy customization
  test/upgrade/continual.go
  test/upgrade/suite.go
Labels: approved, lgtm

#171 [0.22] Setting retries & replication options with easy customization
  test/upgrade/continual.go
  test/upgrade/suite.go
Labels: approved, lgtm

#178 [0.22] Missing defer close kafka admin client
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
Labels: approved, lgtm

#176 [0.20] Missing defer close kafka admin client
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
Labels: approved, lgtm

#175 Fixing version of promoted images and the storage fu
  openshift/release/knative-eventing-kafka-channel-ci.yaml
  openshift/release/knative-eventing-kafka-distributed-channel-ci.yaml
  openshift/release/knative-eventing-kafka-source-ci.yaml
Labels: approved, lgtm

#177 [0.21] Missing defer close kafka admin client
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
Labels: approved, lgtm
